Dex:
  Issuer: https://kubesignin.test.skyscrape.rs/dex
  Connectors:
    GitHub:
    - Name: GitHub
      ClientId: <BASE64_ENCODED_CLIENT_ID>
      ClientSecret: <BASE64_ENCODED_CLIENT_SECRET>
      Org: skyscrapers

Kubesignin:
  ClientSecret: <SOME_RANDOM_STRING>
  RedirectUri: https://kubesignin.test.skyscrape.rs/callback
  DomainName: kubesignin.test.skyscrape.rs

# Kube2iam
host:
  iptables: true
  interface: cali+

# Kube-lego
config:
  LEGO_EMAIL: hello@skyscrapers.eu
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

# Nginx-ingress
controller:
  image:
    tag: "0.9.0-beta.7"
  publishService:
    enabled: true
  rbac:
    enabled: true
  stats:
    enabled: true

ExternalDNS:
  IAMRoleARN: <IAM_ROLE_ARN>
