apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Values.prometheus.app }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    prometheus: {{ .Values.prometheus.name }}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  endpoints:
  - interval: {{ .Values.interval }}
    port: http
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app: elasticsearch-exporter
      release: "{{ .Release.Name }}"
