apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: dex
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dex.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "dex.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.Kubesignin.K8sAdminsGroups }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
{{- range .Values.Kubesignin.K8sAdminsGroups }}
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
