## Prometheus MatchLabel selectors
prometheus:
  labels:
    app: "prometheus"
    role: "alert-rules"
    prometheus: "k8s-monitor"

## Interval for how often Prometheus scrapes the mongodb-exporter
interval: "30s"

mongodbExporter:
  ## number of exporter instances
  ##
  replicaCount: 1

  ## restart policy for all containers
  ##
  restartPolicy: Always

  image:
    repository: "skyscrapers/mongodb-exporter"
    tag: latest
    pullPolicy: IfNotPresent

  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

  service:
    type: ClusterIP
    httpPort: 9001
    annotations: {}

  mongodb:
    dbuser: admin
    dbpass: pass
    dbhost: localhost
    dbport: 27017
    dbname: admin
    collectOplog: true
    collectReplSet: true
    collectTopMetrics: false
    collectDatabaseMetrics: false
    collectCollectionMetrics: false
    collectProfileMetrics: false
    collectConnPoolStats: false
