## Prometheus MatchLabel selectors
prometheus:
  labels:
    app: "prometheus"
    role: "alert-rules"
    prometheus: "k8s-monitor"

## Interval for how often Prometheus scrapes the mongodb-exporter
interval: "30s"

mongodb_exporter:
  deployments:
    first:
      name: mongodb-exporter
      mongodb_uri: "mongodb://admin:pass@localhost:27017/pekarnya"
      mongodb_collect_connpoolstats: "true"
      mongodb_collect_oplog: "true"
  service_name: mongodb-exporter