apiVersion: v1
kind: Secret
metadata:
  name: {{ template "concourse.fullname" . }}
  labels:
    app: {{ template "concourse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresql-user: {{ .Values.concourse.postgresql.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.concourse.postgresql.postgresPassword | b64enc | quote }}
  basic-auth-username: {{ default "" .Values.concourse.username | b64enc | quote }}
  basic-auth-password: {{ default "" .Values.concourse.password | b64enc | quote }}
  github-auth-client-id: {{ default "" .Values.concourse.githubAuthClientId | b64enc | quote }}
  github-auth-client-secret: {{ default "" .Values.concourse.githubAuthClientSecret | b64enc | quote }}
  generic-oauth-client-id: {{ default "" .Values.concourse.genericOauthClientId | b64enc | quote }}
  generic-oauth-client-secret: {{ default "" .Values.concourse.genericOauthClientSecret | b64enc | quote }}
