apiVersion: v1
kind: Service
metadata:
  name: {{ template "web.fullname" . }}
  labels:
    app: {{ template "web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: web
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    dns: route53
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.concourse.web.service.domainName }}.
spec:
  tls:
  - secretName: {{ template "concourse.fullname" . }}-lego-tls
    hosts:
    - {{.Values.concourse.web.service.domainName}}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.concourse.atcPort }}
    - name: tsa
      port: {{ .Values.concourse.tsaPort }}
      targetPort: tsa
  selector:
    app: {{ template "web.fullname" . }}
    release: {{ .Release.Name }}
