apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mongodb-exporter.fullname" . }}
  labels:
    app: {{ template "mongodb-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.mongodbExporter.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "mongodb-exporter.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.mongodbExporter.restartPolicy }}
      containers:
        - name: mongodb-exporter
          image: "{{ .Values.mongodbExporter.image.repository }}:{{ .Values.mongodbExporter.image.tag }}"
          imagePullPolicy: {{ .Values.mongodbExporter.image.pullPolicy | quote }}
          command: ["/usr/local/bin/mongodb_exporter", "-web.listen-address=:{{ .Values.mongodbExporter.service.httpPort }}", "-web.metrics-path=/metrics", "-logtostderr", "-mongodb.uri={{ .Values.mongodbExporter.mongodb.uri }}", "-mongodb.collect.oplog={{ .Values.mongodbExporter.mongodb.collectOplog }}", "-mongodb.collect.replset={{ .Values.mongodbExporter.mongodb.collectReplSet }}", "-mongodb.collect.top={{ .Values.mongodbExporter.mongodb.collectTopMetrics }}", "-mongodb.collect.database={{ .Values.mongodbExporter.mongodb.collectDatabaseMetrics }}", "-mongodb.collect.collection={{ .Values.mongodbExporter.mongodb.collectCollectionMetrics }}", "-mongodb.collect.profile={{ .Values.mongodbExporter.mongodb.collectProfileMetrics }}", "-mongodb.collect.connpoolstats={{ .Values.mongodbExporter.mongodb.collectConnPoolStats }}"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
          - name: http
            containerPort: {{ .Values.mongodbExporter.service.httpPort }}
          livenessProbe:
              httpGet:
                port: http
                path: /metrics
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                port: http
                path: /metrics
